name: deploy hugo pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:      
      - name: build on target
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ./visualprogramming.net/build.sh
          host: 'visualprogramming.net'
          username: vvvv
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
